### ISSUE TITLE
Empty line is removed in property 'text'

### ISSUE THREAD

**Issue by benZhai01** [IgniteUI/typedoc-plugin-localization#33]
I have following comment:
/**
     * Gets or sets the path for the binding.
     *
     * In the simplest case, the path is the name of the property of the source
     * object to use for the binding (e.g. 'street').
     *
     * Sub-properties of a property can be specified by a syntax similar to that
     * used in JavaScript (e.g. 'address.street').
     */
actual result: 
{
    "comment": {
            "text": [
                "Gets or sets the path for the binding. ",
                "In the simplest case, the path is the name of the property of the source",
                "object to use for the binding (e.g. 'street').",
                "Sub-properties of a property can be specified by a syntax similar to that",
                " used in JavaScript (e.g. 'address.street')."
            ],
}

It seems the empty lines are removed in result json.

**Comment by Aleksandyr** [comment]
@benZhai01 That's how the plugin works for now. We can set it as an enactment which would be implemented in the future. 
If you feel confident you are also free to propose a solution for this case.

**Comment by benZhai01** [comment]
@Aleksandyr Thanks for your explaination.
