### ISSUE TITLE
Plugins should export a "load" function to be called with the Application     at Application.bootstrap

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/typedoc-plugin-localization#61]
Future improvements

- Exporting load function instead of module.exports.
Plugins that use @Component (unfortunately basically everything) will be broken once typedoc remove it, so ideally don't use that. The plugin should export function load(host: PluginHost) that TypeDoc will call.
- Remove all initialize methods, it tends to require type assertions that shouldn't be necessary
- Subscribe to events as required. Instead of using **listenTo**, use **on** to avoid needing to inherit the component classes. The events are modified versions of Backbone's events
- **Theming does not support handlebars anymore instead, it uses jsx templating. [Example theme](https://github.com/Gerrit0/typedoc-custom-theme-demo)**

**Comment by zdrawku** [comment]
We are postponing that for the time being
