### ISSUE TITLE
Encode files in UTF8

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/typedoc-plugin-localization#7]
Currently the output files are encoded in ANSI.  Could they please be created in UTF8?  We use UTF8 with BOM to ensure that localized files can contain Unicode characters.

**Comment by Aleksandyr** [comment]
@ig-ealbert Both the json's and the html output files are with same encoding which is UTF8.
![capture](https://user-images.githubusercontent.com/7037740/44778452-a3afaf00-ab85-11e8-8c0f-f0e2ef178492.PNG)
![capture2](https://user-images.githubusercontent.com/7037740/44778453-a4484580-ab85-11e8-879d-b58327db91ef.PNG)

**Comment by ig-ealbert** [comment]
@Aleksandyr Did this change in the last 2 days?  I created the export on 8/27 and all of the .json files are in ANSI.
![image](https://user-images.githubusercontent.com/8162597/44791758-5bd25d00-ab70-11e8-9152-fd79c2c62202.png)
